import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { parseSystemConsoleTheme, SYSTEM_CONSOLE_THEME_KEY, type SystemConsoleTheme } from "@/lib/systemTheme";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, LayoutDashboard, Loader2, LockKeyhole, Moon, Settings2, ShieldCheck, Sun } from "lucide-react";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import { Link, useLocation } from "wouter";

export function SystemAdminShell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const utils = trpc.useUtils();
  const access = trpc.system.access.useQuery();
  const unlock = trpc.system.unlock.useMutation({ onSuccess: () => void utils.system.access.invalidate() });
  const [token, setToken] = useState("");
  const [theme, setTheme] = useState<SystemConsoleTheme>(() => parseSystemConsoleTheme(window.localStorage.getItem(SYSTEM_CONSOLE_THEME_KEY)));
  const dark = theme === "dark";

  useEffect(() => { window.localStorage.setItem(SYSTEM_CONSOLE_THEME_KEY, theme); }, [theme]);
  const toggleTheme = () => setTheme(previous => previous === "dark" ? "light" : "dark");

  if (access.isLoading) return <div className={dark ? "dark" : ""}><div className="grid min-h-screen place-items-center bg-[#f6f5f2] dark:bg-[#111a17]"><Loader2 className="size-6 animate-spin text-[#5d8141] dark:text-[#b5e765]" /></div></div>;
  if (!access.data?.authorized) {
    const submit = async (event: FormEvent) => { event.preventDefault(); try { await unlock.mutateAsync({ token }); setToken(""); } catch { /* surface the error below */ } };
    return <div className={dark ? "dark" : ""}><main className="grid min-h-screen place-items-center bg-[#f6f5f2] px-5 text-[#17201e] dark:bg-[#111a17] dark:text-[#ebf1ea]"><form onSubmit={submit} className="w-full max-w-md rounded-[28px] border border-[#dce5d5] bg-white p-7 shadow-[0_20px_70px_rgba(31,43,37,.1)] dark:border-[#34463e] dark:bg-[#1a2823] dark:shadow-black/20"><div className="mb-5 grid size-11 place-items-center rounded-2xl bg-[#1b2421] text-[#c5f165] dark:bg-[#283a33] dark:text-[#d2f979]"><LockKeyhole size={20} /></div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#74985d] dark:text-[#a8d477]">Cineflow system</p><h1 className="mt-1 font-display text-2xl font-semibold tracking-[-.045em]">Administrator access</h1><p className="mt-2 text-sm leading-6 text-[#68746e] dark:text-[#abb8b1]">ป้อน administrator token ที่กำหนดไว้ตอนติดตั้ง เพื่อดูสถานะระบบหรือเปลี่ยน provider credentials ได้อย่างปลอดภัย</p><label className="mt-6 block text-xs font-semibold text-[#405046] dark:text-[#d0d9d3]">ADMINISTRATOR TOKEN<Input type="password" autoComplete="current-password" value={token} onChange={event => setToken(event.target.value)} className="mt-2 h-11 border-[#d6ded1] bg-[#fbfcfa] dark:border-[#3b4e45] dark:bg-[#12201a] dark:text-[#eef4ef]" placeholder="Paste deployment admin token" /></label>{unlock.isError && <p className="mt-3 flex items-center gap-1.5 text-xs text-rose-700 dark:text-rose-300"><AlertTriangle size={14} /> {unlock.error.message}</p>}<Button type="submit" disabled={!token || unlock.isPending} className="mt-5 h-11 w-full bg-[#244337] text-white hover:bg-[#315849] dark:bg-[#b5e765] dark:text-[#17221d] dark:hover:bg-[#c5f77a]">{unlock.isPending ? <Loader2 className="animate-spin" /> : <ShieldCheck />} Unlock system console</Button><Link href="/" className="mt-4 block text-center text-xs font-medium text-[#668151] hover:underline dark:text-[#b0d982]">กลับไปที่ video editor</Link></form></main></div>;
  }

  return <div className={dark ? "dark" : ""}><div className="min-h-screen bg-[#f6f5f2] text-[#17201e] dark:bg-[#111a17] dark:text-[#ebf1ea]"><header className="border-b border-[#e7e4de] bg-[#fbfaf8]/90 backdrop-blur-xl dark:border-[#304039] dark:bg-[#16231e]/90"><div className="mx-auto flex min-h-[76px] max-w-[1280px] flex-wrap items-center justify-between gap-3 px-5 py-3 lg:px-10"><Link href="/" className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#152b27] text-[#c5f165] dark:bg-[#2a4036] dark:text-[#d4f878]"><ShieldCheck size={19} /></div><div><p className="font-display text-[17px] font-semibold tracking-[-.04em]">Cineflow</p><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#77827f] dark:text-[#9faea6]">SYSTEM CONSOLE</p></div></Link><div className="flex items-center gap-2"><nav className="flex items-center gap-1 rounded-xl border border-[#dce5d5] bg-white p-1 text-xs font-semibold dark:border-[#36483f] dark:bg-[#1d2c26]"><Link href="/system" className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-2 transition ${location === "/system" ? "bg-[#edf5dd] text-[#45672f] dark:bg-[#324b35] dark:text-[#d4f979]" : "text-[#69766f] hover:bg-[#f4f6f0] dark:text-[#b1bcb6] dark:hover:bg-[#293a32]"}`}><LayoutDashboard size={14} /> Dashboard</Link><Link href="/settings" className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-2 transition ${location === "/settings" ? "bg-[#edf5dd] text-[#45672f] dark:bg-[#324b35] dark:text-[#d4f979]" : "text-[#69766f] hover:bg-[#f4f6f0] dark:text-[#b1bcb6] dark:hover:bg-[#293a32]"}`}><Settings2 size={14} /> Settings</Link></nav><Button type="button" variant="outline" size="icon" onClick={toggleTheme} aria-label={dark ? "Switch to light mode" : "Switch to dark mode"} title={dark ? "Light mode" : "Dark mode"} className="size-9 border-[#dce5d5] bg-white text-[#54704e] hover:bg-[#eff5e8] dark:border-[#36483f] dark:bg-[#1d2c26] dark:text-[#d4f979] dark:hover:bg-[#293a32]">{dark ? <Sun size={16} /> : <Moon size={16} />}</Button></div></div></header><main className="mx-auto max-w-[1280px] px-5 py-7 lg:px-10 lg:py-9">{children}</main></div></div>;
}
